mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL

spring:

  datasource:

    url: jdbc:log4jdbc:mariadb://svc.sel5.cloudtype.app:31389/doctor
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: k841101!@#
